### PR TITLE
 OpenPaaS-Suite/esn-frontend-calendar#51 implement dav import API 

### LINKED ISSUE #51: Import menu entry does not work
The calendar (+) button -> **Import** does not work.

Error in the console:
```
angular-strap.js:2501 Error: [$injector:unpr] Unknown provider: davImportServiceProvider <- davImportService <- CalCalendarImportController
http://errors.angularjs.org/1.3.20/$injector/unpr?p0=davImportServiceProvider%20%3C-%20davImportService%20%3C-%20CalCalendarImportController
```

### PR DESCRIPTION
**Pull request by tuanlc**
Partial resolve https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/51

### CODE REVIEW

File: src/api/dav-import.js [hunk 1]
```diff
@@ -0,0 +1,20 @@
+const BASE_PATH = '/import';
+
+export default function(client) {
```
Comment (piavgh) [inline src/api/dav-import.js:3]: where is this `client` parameter injected?

Comment (tuanlc) [reply src/api/dav-import.js:3]: Please check the readme for the usage documentation ;)

**Review by itswillta — APPROVED** [review]

File: src/api/dav-import.js (hunk 1 above)
Comment (piavgh) [reply src/api/dav-import.js:3]: ok, got it :D

**Review by piavgh — APPROVED** [review]

**Review by chamerling — APPROVED** [review]
